blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/samuraiii/PuppetNetworkManagerModule/security/advisories/new
    about: Please do not report security issues in a public issue.
